server:
    port: 8181

security:
    basic:
        enabled: false

        
logging:
  level:
    org:
      springframework:
        security: DEBUG
spring:
  data:
    jpa:
      repositories:
        enabled: false          
  thymeleaf:
    cache: false
    mode: LEGACYHTML5